# ========== POSTGRES CENTRAL ==========
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-central-pvc
  namespace: agroflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-central
  namespace: agroflow
spec:
  selector:
    matchLabels:
      app: postgres-central
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-central
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: agroflow_central
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Edgar123456/
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 200m
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-central-pvc
---
# ========== MYSQL INVENTARIO ==========
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-inventario-pvc
  namespace: agroflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-inventario
  namespace: agroflow
spec:
  selector:
    matchLabels:
      app: mysql-inventario
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-inventario
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: db_inventario
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_USER
              value: inventario_user
            - name: MYSQL_PASSWORD
              value: inventario_pass
          args:
            - "--default-authentication-plugin=mysql_native_password"
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "mysqladmin ping -h localhost -u root -prootpassword"
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "mysqladmin ping -h localhost -u root -prootpassword"
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 300m
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mysql-inventario-pvc
---
# ========== POSTGRES FACTURACION ==========
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-facturacion-pvc
  namespace: agroflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-facturacion
  namespace: agroflow
spec:
  selector:
    matchLabels:
      app: postgres-facturacion
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-facturacion
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: agroflow_facturacion
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Edgar123456/
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 200m
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-facturacion-pvc